### ISSUE TITLE
Where is the query type classification for TPC-DS queries?

### ISSUE THREAD

**Issue by krdeepakio** [gregrahn/tpcds-kit#15]
The queries are categorized into four types and few examples are there.

Reporting Class 41
Ad Hoc Class 59
Iterative Class 4
Data Mining Class 23 

I did not find the type of each query anywhere. One hint is that store_sales queries are ad-hoc and catalog_sales are reporting. There is no other data point to classify the queries.

**Comment by dleybz** [comment]
Is there any update on this? Also interested.

**Comment by gregrahn** [comment]
Where did these categories come from?

**Comment by dleybz** [comment]
TPC-DS mentions a categorization multiple times. For insance, in Section 4.1 of [this document](http://www.tpc.org/tpcds/presentations/tpcds_workload_analysis.pdf) "Reporting", "Ad Hoc", "Iterative", and "Data Mining" classes are referred to but not defined.

**Comment by gregrahn** [comment]
Thanks @dleybz.  There is a reference to these also in the [spec](http://www.tpc.org/tpc_documents_current_versions/pdf/tpc-ds_v2.1.0.pdf) in section 1.4.1 but no mapping of query name/number to query class that I see.  Bummer.

**Comment by dleybz** [comment]
Very odd that they seem to have a consistently named and even defined schema, but don't provide this mapping anywhere as far as I can tell.

**Comment by leonardBang** [comment]
Did you finally find the mapping?  I met this issue too.

**Comment by tharsha18** [comment]
Here is what i have been using for years

TPCDS Query classification:
discovery/Interactive (ad-hoc) - q19, q42, q52, q55, q63, q68, q73, q98

BI Reporting - q3, q7, q27, q43, q53, q89
	
Analytics - q34, q46, q59, q79, q96, q48
