### ISSUE TITLE
How are validation queries generated using substitution parameters?

### ISSUE THREAD

**Issue by krdeepakio** [gregrahn/tpcds-kit#16]
There is an answer_sets folder but it does not work for normal queries generated using scale factor 1. We need to change substitution parameters (section 11 appendix B of TPCDS.1.3.1.pdf doc) after which results match. I could not find any automated way to do this.
Is there an option in dsqgen to generate validation queries using correct substitution parameters for scale factor 1 so that validation can be done?

**Comment by rogargon** [comment]
About to report an issue about expected answers in the answer_sets folder not matching the results I was getting with the corresponding queries. However, I suppose this is related with this issue... 

For instance, for Query 96 the expected output is "870" in 96.ans but I'm getting consistently "949" with MySQL or Postgres and both TPC-DS 2.1 and 2.3

**Comment by gregrahn** [comment]
@rogargon Can you share the `dsdgen` and `dsqgen` commands you've used?

**Comment by rogargon** [comment]
dsdgen -dir ../data/scale_1 -scale 1 -terminate N

dsqgen -directory ../query_templates -scale 1 -input
../query_templates/templates.lst -dialect netezza

**Comment by gregrahn** [comment]
Unfortunately the default substitution parameters have to be added by hand per section 4.3.2 (page 45).
> **Comment:** The substitution parameter values for the qualification queries are provided in 11.9.1.1Appendix B:. They must be manually inserted into the query templates.
