### ISSUE TITLE
Select rename column should contain "AS"

### ISSUE THREAD

**Issue by fzqneo** [gregrahn/tpcds-kit#17]
When aliasing a column in SELECT query, I believe the word "AS" is the standard SQL (e.g., `select sum(x) AS s`). Though some system allow omitting it, others don't, such as MonetDB.

The current template files don't have AS when aliasing a column. I think it is desired to add it. 

Edit: I just find "AS" is missing only in some queries, e.g., query3.

**Comment by gregrahn** [comment]
Although not considered bugs in the query templates, syntax changes like this are considered minor query modifications, and are permitted w/o approval per section 4.2.3 of the spec.
