### ISSUE TITLE
Error in query77.tpl and query77a.tpl

### ISSUE THREAD

**Issue by raghavsood33** [gregrahn/tpcds-kit#20]
The query77 and its variant has a slight error. 
https://github.com/gregrahn/tpcds-kit/blob/master/query_templates/query77.tpl#L135
https://github.com/gregrahn/tpcds-kit/blob/master/query_variants/query77a.tpl#L136

to fix replace `, coalesce(returns, 0) returns` by `, coalesce(returns, 0) as returns`

PS: I am unauthorized to push the fix

**Comment by gregrahn** [comment]
Although not considered bugs in the query templates, syntax changes like this are considered minor query modifications, and are permitted w/o approval per section 4.2.3 of the spec.
See #17

**Comment by raghavsood33** [comment]
But in the same query77 we have `coalesce(returns, 0) as returns` and `(profit - coalesce(profit_loss,0)) as profit` at 3 other places which is correct while at one place `as` seems missing. 
[#17](https://github.com/gregrahn/tpcds-kit/issues/17) I believe is little different as it is about aliasing subqueries in general.

**Comment by gregrahn** [comment]
Any expression alias, be it column, table, or subquery, falls under section 4.2.3.4 and is considered a minor query modification and is permitted.  I do agree that aliasing is very inconsistent, even within a given query, but given it can be changed w/o approval it's not really an issue IMHO.  Also, some query engines will run these w/o any modifications, so it makes it more of a query engine specific modification.
