### ISSUE TITLE
"Error: open of distributions failed: tpcds.idx: No such file or directory"

### ISSUE THREAD

**Issue by eisenwang** [gregrahn/tpcds-kit#21]
Dear All,

   I just downloaded the most recent tpcds-kit-master. I first tested with --
/asiq160/rs/tpc-ds/tpcds-kit-master/tools/dsqgen -template query99.tpl -dir /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates -dialect sybase
  It works fine and generate a valid sql file. But while I ran --
/asiq160/rs/tpc-ds/tpcds-kit-master/tools/dsqgen -template query98.tpl -dir /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates -dialect sybase
 It raised error as --
qgen2 Query Generator (Version 2.3.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2016
Error: open of distributions failed: tpcds.idx: No such file or directory

   I don't know if it's due to query98.tpl is not in the list... And the batch statement -- 
/asiq160/rs/tpc-ds/tpcds-kit-master/tools/dsqgen -input /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates/templates.lst -scale 8 -dialect sybase -directory /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates

    Also raised the same error --
asiq160@bigDataIQ:/iq_data/dump/query> /asiq160/rs/tpc-ds/tpcds-kit-master/tools/dsqgen -input /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates/templates.lst -scale 8 -dialect sybase -directory /asiq160/rs/tpc-ds/tpcds-kit-master/query_templates
qgen2 Query Generator (Version 2.3.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2016
Error: open of distributions failed: tpcds.idx: No such file or directory

    So maybe due to the tpcds.idx not contains all the 99 templates? Please kind help. Thanks in advance for your help.

Regards
Eisen

**Comment by gregrahn** [comment]
The problem is that `dsdgen` needs to read `tpcds.idx` and it assumes it is in the current directory.  If that is not the case, then you need to use the `-DISTRIBUTIONS` flag to tell it the path.

**Comment by eisenwang** [comment]
Thank you very much.
