### ISSUE TITLE
FILTER flag no longer working

### ISSUE THREAD

**Issue by schaffino** [gregrahn/tpcds-kit#25]
It seems that with the recent changes the FILTER flag for dsdgen no longer ouputs to STDOUT. __FILTER is still listed but data is output to local dir.

**Comment by gregrahn** [comment]
The stdout stuff is broken now (and never worked correctly for all the tables).  If you want the previous version then this should get you there:
```
git clone https://github.com/gregrahn/tpcds-kit.git
cd tpcds-kit
git reset --hard eff5de2c30337b71cc0dc1976147742d2c65d378
```
Perhaps your question is also related to this:
https://github.com/cloudera/impala-tpcds-kit/issues/19#issuecomment-249312729

**Comment by gregrahn** [comment]
Just updated the [cloudera/impala-tpcds-kit/README.md](https://github.com/cloudera/impala-tpcds-kit/blob/master/README.md) via https://github.com/cloudera/impala-tpcds-kit/commit/b5cef1116df26104895dbabbf70d419f0cc94af2
