### ISSUE TITLE
y.tab.h not found

### ISSUE THREAD

**Issue by robins** [gregrahn/tpcds-kit#27]
Looks like a recent change broke this:

[ec2@ip-111 tools]$ make
yacc -d -v qgen.y
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall   -c -o expr.o expr.c
expr.c:49:19: fatal error: y.tab.h: No such file or directory
 #include "y.tab.h"
                   ^
compilation terminated.
make: *** [expr.o] Error 1
[ec2@ip-111 tools]$

(I have the instance around, let me know if you want me to test something out)

**Comment by gregrahn** [comment]
Be sure to install the prerequisite tools (I'll make a README soon for this).  My guess is you are missing `yacc`.

For Ubuntu: `sudo apt-get install gcc make flex bison byacc git`
For CentOS/RHEL: `sudo yum install gcc make flex bison byacc git`

The following worked fine for me on Ubuntu 16.04:
```
sudo apt-get install gcc make flex bison byacc git
git clone https://github.com/gregrahn/tpcds-kit.git
cd tpcds-kit/tools
make OS=LINUX
```
```
grahn@ubuntu:~/tpcds-kit/tools$ ls -l ds*
-rwxrwxr-x 1 grahn grahn 462008 Mar  5 08:45 dsdgen
-rwxrwxr-x 1 grahn grahn 292520 Mar  5 08:45 dsqgen
```

**Comment by robins** [comment]
Thanks (closing the issue). It's weird because I've used this earlier on this system and unless this was a recent change, I was assuming this system already had the required software.
