### ISSUE TITLE
When I make the code, I will make a mistake.

### ISSUE THREAD

**Issue by guchao-repository** [gregrahn/tpcds-kit#32]
When I make the code, I will make a mistake.

`[root@master tools]# make
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o dsqgen address.o date.o decimal.o dist.o error_msg.o expr.o eval.o genrand.o grammar_support.o keywords.o list.o nulls.o permute.o print.o QgenMain.o query_handler.o r_params.o scaling.o StringBuffer.o substitution.o tdefs.o text.o tokenizer.o w_inventory.o y.tab.o release.o scd.o build_support.o parallel.o  -lm
grammar_support.o: In function `include_file':
/opt/tpcds-kit-master/tools/grammar_support.c:128: undefined reference to `yy_create_buffer'
/opt/tpcds-kit-master/tools/grammar_support.c:129: undefined reference to `yy_switch_to_buffer'
y.tab.o: In function `yyparse':
/opt/tpcds-kit-master/tools/y.tab.c:551: undefined reference to `yylex'
/opt/tpcds-kit-master/tools/y.tab.c:1129: undefined reference to `yylex'
collect2: ld returned 1 exit status
make: *** [dsqgen] Error 1`

I need help to solve this issue. Thanks.

**Comment by gregrahn** [comment]
Seems like missing dev tools.  See #27

**Comment by guchao-repository** [comment]
@gregrahn Thank you for your reply. It doesn't work.

[root@master tools]# yum install gcc make flex bison byacc git
Loaded plugins: fastestmirror
Setting up Install Process
Loading mirror speeds from cached hostfile
 * base: mirrors.sohu.com
 * extras: mirrors.btte.net
 * updates: mirrors.sohu.com
Package gcc-4.4.7-18.el6.x86_64 already installed and latest version
Package 1:make-3.81-23.el6.x86_64 already installed and latest version
Package flex-2.5.35-9.el6.x86_64 already installed and latest version
Package bison-2.4.1-5.el6.x86_64 already installed and latest version
Package byacc-1.9.20070509-7.el6.x86_64 already installed and latest version
Package git-1.7.1-8.el6.x86_64 already installed and latest version
Nothing to do

[root@master tools]# make OS=LINUX
make: *** No targets specified and no makefile found.  Stop.

[root@master tools]# cp Makefile.suite Makefile
[root@master tools]# make
gcc -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -DYYDEBUG  -DLINUX -g -Wall  -o dsqgen address.o date.o decimal.o dist.o error_msg.o expr.o eval.o genrand.o grammar_support.o keywords.o list.o nulls.o permute.o print.o QgenMain.o query_handler.o r_params.o scaling.o StringBuffer.o substitution.o tdefs.o text.o tokenizer.o w_inventory.o y.tab.o release.o scd.o build_support.o parallel.o  -lm
grammar_support.o: In function `include_file':
/opt/tpcds-kit-master/tools/grammar_support.c:128: undefined reference to `yy_create_buffer'
/opt/tpcds-kit-master/tools/grammar_support.c:129: undefined reference to `yy_switch_to_buffer'
y.tab.o: In function `yyparse':
/opt/tpcds-kit-master/tools/y.tab.c:551: undefined reference to `yylex'
/opt/tpcds-kit-master/tools/y.tab.c:1129: undefined reference to `yylex'
collect2: ld returned 1 exit status
make: *** [dsqgen] Error 1

**Comment by gregrahn** [comment]
What is the OS and version?
Did you also `make clean`?

**Comment by guchao-repository** [comment]
@gregrahn I forget to run "make clean". Now it works. Thanks.
