### ISSUE TITLE
ERROR: Malloc Failed at 116 in permute.c

### ISSUE THREAD

**Issue by estebgonza** [gregrahn/tpcds-kit#37]
Hi gregrahn,

Thank you for this repository 🥇 
I have an error after this:
`dsqgen \
-DIRECTORY ../query_templates \
-INPUT ../query_templates/templates.lst \
-VERBOSE Y \
-QUALIFY Y \
-SCALE 10000 \
-DIALECT netezza \
-OUTPUT_DIR /tmp`

I have in output:
`qgen2 Query Generator (Version 2.6.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2017
Parsed 99 templates
Malloc Failed at 116 in permute.c`

Have you ever had this error?
Thank you!

**Comment by gregrahn** [comment]
What version of OS and compiler you are on?

Quick workaround is to remove `query9.tpl` from `query_templates/templates.lst` which will let you generate the other 98 queries.

Requires more analysis.  Thanks.

**Comment by gregrahn** [comment]
This issue has been reported to the TPC.
Details:

It looks like there is some search space blow up an issue related to query9.  As the SF increases dsqgen allocates quite a significant amount of memory and the execution time increases as well.

If I run `/usr/bin/time -v ./dsqgen ...` for each of the SF (1 1000 3000 10000 30000) the result is the following.  Probably worth investigating - after all, 6m16s to generate 1 query at SF 30000 seems pretty broken (or at least far from efficient).  To generate the other 98 queries at SF30000 it takes less than 1 second for comparison. 
```
$ egrep '(Maximum resident set size|User time)' dsqgen.txt
  User time (seconds): 0.00
  Maximum resident set size (kbytes): 4976
  User time (seconds): 11.11
  Maximum resident set size (kbytes): 1503488
  User time (seconds): 24.59
  Maximum resident set size (kbytes): 4503488
  User time (seconds): 115.52
  Maximum resident set size (kbytes): 15003488
  User time (seconds): 376.16
  Maximum resident set size (kbytes): 45003472
```
```
Call graph:
    893 Thread_5220409   DispatchQueue_1: com.apple.main-thread  (serial)
      893 start  (in libdyld.dylib) + 1  [0x7fff7ddd1115]
        893 main  (in dsqgen) + 487  [0x106d02c57]  QgenMain.c:369
          893 generateQueryStreams  (in dsqgen) + 782  [0x106d0295e]  QgenMain.c:297
            893 GenerateQuery  (in dsqgen) + 939  [0x106d0335b]  query_handler.c:271
              893 EvalExpr  (in dsqgen) + 1828  [0x106cfec54]  eval.c:865
                893 EvalRandomExpr  (in dsqgen) + 471  [0x106cfce77]  eval.c:250
                  812 makeKeyPermutation  (in dsqgen) + 309,313,...  [0x106d00ec5,0x106d00ec9,...]  permute.c:126
                  54 makeKeyPermutation  (in dsqgen) + 337,325  [0x106d00ee1,0x106d00ed5]  permute.c:127
                  23 makeKeyPermutation  (in dsqgen) + 341,349  [0x106d00ee5,0x106d00eed]  permute.c:122
                  3 makeKeyPermutation  (in dsqgen) + 281  [0x106d00ea9]  permute.c:124
                  + 2 genrand_key  (in dsqgen) + 102  [0x106cff0e6]  genrand.c:228
                  + ! 2 next_random  (in dsqgen) + 33,46  [0x106cfed61,0x106cfed6e]  genrand.c:83
                  + 1 genrand_key  (in dsqgen) + 329  [0x106cff1c9]  genrand.c:243
                  1 makeKeyPermutation  (in dsqgen) + 297  [0x106d00eb9]  permute.c:125

Total number in stack (recursive counted multiple, when >=5):

Sort by top of stack, same collapsed (when >= 5):
        makeKeyPermutation  (in dsqgen)        890
```
