### ISSUE TITLE
MySQL issue

### ISSUE THREAD

**Issue by pedrogcsb** [gregrahn/tpcds-kit#40]
Hello,
Is there any way to generate queries to use on MySQL? I've trying to use the netezza template but ERROR 1064 pops up on almost every single query. I'm just starting to use it so I'm rookie. Any help? Can't use other DBMS since it's a school project.

Best regards

**Comment by gregrahn** [comment]
The Netezza template simply is used to specify the correct SQL syntax for limiting results.  Eg. `limit 10`.  MySQL supports that syntax, however, there are likely other SQL language modifications needed for MySQL.  The 1064 error is just a generic error that there is some syntax that MySQL does not support.  Likely things like data math syntax are causing it.  Just adjust those to be an equivalent and supported syntax for MySQL.
