### ISSUE TITLE
Failed to open output file

### ISSUE THREAD

**Issue by czelaznog** [gregrahn/tpcds-kit#44]
Hi gregrahn,

I am getting this error. Any idea how can I fix it?

dsdgen Population Generator (Version 2.10.0)
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Warning: Selected scale factor is NOT valid for result publication
Warning: Selected scale factor is NOT valid for result publication
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Warning: Selected scale factor is NOT valid for result publication
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Warning: Selected scale factor is NOT valid for result publication
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Warning: Selected scale factor is NOT valid for result publication
[ec2-user@ip-10-0-0-131 hands-on-with-redshift]$ Warning: Selected scale factor is NOT valid for result publication
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
dsdgen Population Generator (Version 2.10.0)
Copyright Transaction Processing Performance Council (TPC) 2001 - 2018
Warning: Selected scale factor is NOT valid for result publication
Warning: Selected scale factor is NOT valid for result publication
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490
ERROR: Failed to open output file!
	File: print.c
	Line: 490

**Comment by gregrahn** [comment]
It's difficult to guess -- can you include the exact command line being used?

**Comment by Peter-Ebert** [comment]
my guess is the output dir was not created, might want to add that step to the readme or have the code create the dir if it does not exist

**Comment by gregrahn** [comment]
Added in 7fcaf27
