### ISSUE TITLE
TPC-DS database problems with foreign keys in MySQL

### ISSUE THREAD

**Issue by ivars31** [gregrahn/tpcds-kit#8]
Hi, I am using TPC-DS and I already uploaded the data generated with dsgen to the Database. However, when I try to run tpcds_ri.sql to include the foreign keys in the system I have several violations of these constraints. Is there any recommendation to avoid this problem? Should I follow a different process to implement these foreign key constraints?
I am generating a 1 GB database. 
Thanks

**Comment by krdeepakio** [comment]
I was trying to do the test using mysql. I did not find the option of mysql as a dialect while generating queries. The other dialects are not compatible. Is there a way to generated all the queries for mysql. Thanks.
